# Generated by Django 3.1.14 on 2022-06-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('somthing_else', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
