# Generated by Django 4.0.5 on 2022-07-18 11:33

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contact_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=50, validators=[home.models.validate_geeks_mail])),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='customers/images')),
            ],
        ),
    ]
