# Generated by Django 4.0.5 on 2022-07-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_customer_last_name_alter_musician_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(choices=[('Ustad Bismillah', 'Ustad Bismillah'), ('R.D. Burman', 'R.D. Burman'), ('ARR', 'AR Rahman')], max_length=50),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(blank=True, choices=[('Guitar', 'Guitar'), ('Violin', 'Violin'), ('Drums', 'Drums')], max_length=50, null=True),
        ),
    ]
