# Generated by Django 4.0.5 on 2022-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_plant_plant_category_alter_plant_plant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_discount_price',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_available',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_subcategory',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=50),
        ),
    ]
