# Generated by Django 4.0.5 on 2022-07-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_plant_plant_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('B', 'Both')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_subcategory',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('B', 'Both')], max_length=50),
        ),
    ]
