# Generated by Django 4.0.5 on 2022-07-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_plant_plant_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
