# Generated by Django 4.0.5 on 2022-07-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_contact_username_alter_plant_plant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
