# Generated by Django 4.0.5 on 2022-07-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
    ]
